# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='idd',
            field=models.IntegerField(default=1),
        ),
    ]
