# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ingredientcategory_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ingredientcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='dishtype',
            name='idd',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='idd',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='idd',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
