# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171209_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishtype',
            old_name='idd',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='idd',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ingredientcategory',
            old_name='idd',
            new_name='id',
        ),
    ]
