# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171210_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='nutrition',
        ),
    ]
